name: pinterest
description: "A pixel-perfect Pinterest clone built with Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Networking
  dio: ^5.7.0

  # Image Caching
  cached_network_image: ^3.4.1

  # Loading Effects
  shimmer: ^3.0.0

  # Grid Layout
  flutter_staggered_grid_view: ^0.7.0

  # Typography
  google_fonts: ^6.2.1

  # Environment Variables
  flutter_dotenv: ^5.2.1

  # Icons
  cupertino_icons: ^1.0.8

  # Authentication
  clerk_flutter: 0.0.14-beta

  # Utilities
  url_launcher: ^6.3.1
  flutter_cache_manager: ^3.4.1
  share_plus: ^10.1.4
  shared_preferences: ^2.3.4
  image_picker: ^1.1.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
